### ISSUE TITLE
Gdrive use FileId to manipulate data instead of file name

### ISSUE THREAD

**Issue by junaire** [beyondstorage/go-service-gdrive#11]
Everything in the Google drive has a unique ID, and their names can actually be duplicate. So Google drive API use `FileId` instead of file name to manipulate data. This can cause a problem. When we call `Write`, gdrive will not give us errors or overwrite the file but simply create another file with the same name if we try to write to an existing file. What we gonna do about this? I guess this will also affect other operations like `Delete` etc.

**Comment by Xuanwo** [comment]
> So Google drive API use `FileId` instead of file name to manipulate data. This can cause a problem.

Yes, it's a limitation according to our path-based API.

So we have to make it clear that we assume the user doesn't have such duplicated path. And we need some conversion between file id and path.

For example, `stat("abc/def")` is not a trivial work, we need (maybe, I'm not so familiar with google drive's API):

- get the fileid about `abc` via `Files.list`.
- get the fileid about `def` via `Files.list`.
- get the metadata of `def` via `Files.get`.

Maybe we can cache the map of `filepath => fileid` in memory to reduce the roundtrip?

> When we call `Write`, gdrive will not give us errors or overwrite the file but simply create another file with the same name if we try to write to an existing file.

As described in [GSP-134](https://github.com/beyondstorage/go-storage/blob/master/docs/rfcs/134-write-behavior-consistency.md), we have to `stat("abc")` before `write("abc")` to avoid creating new files.

> I guess this will also affect other operations like `Delete` etc.

Maybe we can return the `conflict` error if there are duplicated paths?

---

gdrive API is so different from `go-storage` requirement, how about starting an RFC here like https://github.com/beyondstorage/beyond-fs/pull/5 so that we can make all the above concerns clear?

**Comment by junaire** [comment]
>So we have to make it clear that we assume the user doesn't have such duplicated path.

OK, I think we can prohibit users to create files with the same name. When users call `Write` to an existing file, We update it instead of creating another one. [drive/api/v3/reference/files/update](https://developers.google.com/drive/api/v3/reference/files/update)

>And we need some conversion between file id and path.

Yes, we do need it, and recently I'm trying to find a way to do this. 

>Maybe we can cache the map of filepath => fileid in memory to reduce the roundtrip?

I'm not sure whether we need it or not, and how to implement this if we do. When call `Write` to a new file, We can get `FileId` of the file we created, and we can store it to a map. But what if the program crashes? Then we will lost all the info. Personally I prefer use a function to convert file id and path every time we call `Write`, `Delete` etc. However, open discussion :-)

>gdrive API is so different from go-storage requirement, how about starting an RFC here like beyondstorage/beyond-fs#5 so that we can make all the above concerns clear?

This is cool! Gdrive has many notions that differs from `go-storage`, like [scopes](https://developers.google.com/drive/api/v3/about-auth), In fact I'm still trying figure them out. It will be great if we can make everything clear first.

**Comment by junaire** [comment]
close this via #14
